# Run this with docker-compose up 
version: "2"

services:
  # IGNITE
  ignite:
    image: aspnetcore.ignite-server
    hostname: ignite
    networks:
      - aspnetcore.cluster_lan
#    ports:
#      - "127.0.0.1:10800:10800" # For Ignite client mode connections (ODBC?)
#      - "127.0.0.1:47100:47100" # SpiCommunication
#      - "127.0.0.1:47500:47500" # TcpSpiDiscovery
    
networks:
  aspnetcore.cluster_lan:
    driver: macvlan
    driver_opts:
      parent: "Ethernet NES"
    ipam:
      config:
        - subnet: 192.168.76.0/24
          gateway: 192.168.76.1
          ip_range: 192.168.76.32/28 # IP from this pool are assigned automatically   